### ISSUE TITLE
what issue you have ?

### ISSUE THREAD

**Issue by ermi-dev-sec** [mhona/monaa#1]

**Comment by ermi-dev-sec** [comment]
tell me one by one?

**Comment by mhona** [comment]
am working on facebook clone and The feed is stuck at the bottom

**Comment by ermi-dev-sec** [comment]
i fix it for you 2 day ago bro

**Comment by ermi-dev-sec** [comment]
and  i give you bootstrap framework grid layout system

**Comment by mhona** [comment]
i added somethings check  it again

**Comment by ermi-dev-sec** [comment]
so i see your source code why are you using static codes fb use a backend to generate there data or this project is just for UI training 

i can give you hints  
we can add php
or node for your backend

**Comment by ermi-dev-sec** [comment]
and there we can build our Ui based on fb and generate  back
end data based on fb

**Comment by ermi-dev-sec** [comment]
and there we can build our Ui based on fb and generate  back
end data based on fb

**Comment by ermi-dev-sec** [comment]
lets work on our clone database first
